version: "3"
services:
  node:
    container_name: nodeapp
    image: devlegacy/node:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
